# LIBTRANSISTOR OBJECTS HELPER
#  (included from transistor.mk)

libtransistor_OBJECT_NAMES := \
	address_space.o \
	alloc_pages.o \
	crt0_common.o \
	display/binder.o \
	display/display.o \
	display/graphic_buffer_queue.o \
	display/parcel.o \
	display/surface.o \
	environment.o \
	fs/blobfd.o \
	fs/fs.o \
	fs/fspfs.o \
	fs/mountfs.o \
	fs/squashfs.o \
	gfx/blit.o \
	gpu/gpu.o \
	hid.o \
	ipc/am.o \
	ipc/audio.o \
	ipc/bpc.o \
	ipc/bsd.o \
	ipc/fatal.o \
	ipc/fs/idirectory.o \
	ipc/fs/ifile.o \
	ipc/fs/ifilesystem.o \
	ipc/fs.o \
	ipc/hid.o \
	ipc/nifm.o \
	ipc/nv.o \
	ipc.o \
	ipc/pm.o \
	ipc/ro.o \
	ipcserver.o \
	ipc/sm.o \
	ipc/time.o \
	ipc/twili.o \
	ipc/usb/ds/endpoint.o \
	ipc/usb/ds/interface.o \
	ipc/usb.o \
	ipc/vi.o \
	ld/discover.o \
	ld/dlfcn.o \
	ld/elf.o \
	ld/ld.o \
	ld/loader/elf.o \
	ld/loader/nro_via_ldr_ro.o \
	ld/loader/nro_via_svc.o \
	ld/relocate.o \
	ld/resolve.o \
	loader_config.o \
	lz4.o \
	mutex.o \
	sha256.o \
	squashfs/cache.o \
	squashfs/decompress.o \
	squashfs/dir.o \
	squashfs/file.o \
	squashfs/fs.o \
	squashfs/hash.o \
	squashfs/nonstd-pread.o \
	squashfs/nonstd-stat.o \
	squashfs/stack.o \
	squashfs/swap.o \
	squashfs/table.o \
	squashfs/traverse.o \
	squashfs/util.o \
	squashfs/xattr.o \
	strtold.o \
	svc.o \
	syscalls/fd.o \
	syscalls/phal.o \
	syscalls/sched.o \
	syscalls/socket.o \
	syscalls/syscalls.o \
	thread.o \
	tls.o \
	tls_support.o \
	usb_serial.o \
	util.o \
	waiter.o

libtransistor_CPP_OBJECT_NAMES := \
	address_space.o \
	ipcclient.o \
	ipc/hid.o \
	ipcserver.o \
	ipc/sm.o \
	ipc/usb_ds.o \
	svc.o \
	types.o \
	waiter.o
